### ISSUE TITLE
error when inserting a header into a file

### ISSUE THREAD

**Issue by WitekS** [TuXiaokang/codeheader#1]
I am getting this error

`command 'codeheader.insertHeader' not found`

after uninstalling and reinstalling it behaves the same as if nothing happened, the update does not work as if nothing worked ...
I checked for js and php files

**Comment by TuXiaokang** [comment]
thanks for using, and this problem has been solved in the newest version (v0.1.5).  plz update it.

**Comment by WitekS** [comment]
OK it works
thanks for fast reaction
